# Generated by Django 2.0 on 2018-01-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('owner', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
