# Generated by Django 2.0.1 on 2018-02-14 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField()),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa_web.Answers')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa_web.Comments')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa_web.Questions')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='voters',
            field=models.ManyToManyField(related_name='a_voters', through='qa_web.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='voters',
            field=models.ManyToManyField(related_name='c_voters', through='qa_web.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='voters',
            field=models.ManyToManyField(related_name='q_voters', through='qa_web.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
