# Generated by Django 2.0.1 on 2018-02-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qa_web.Post')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            bases=('qa_web.post',),
        ),
    ]
