# Generated by Django 2.0.1 on 2018-02-23 02:20

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('qa_web', '0002_auto_20180214_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
