# Generated by Django 2.0 on 2018-02-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_web', '0002_auto_20180214_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='motherland',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
