# Generated by Django 2.0.1 on 2018-02-23 05:57

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qa_web', '0003_questions_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
