# Generated by Django 2.0.1 on 2018-03-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_web', '0003_auto_20180222_1834'),
        ('qa_web', '0004_auto_20180223_0057'),
    ]

    operations = [
    ]
