# Generated by Django 2.0 on 2018-03-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_web', '0005_merge_20180302_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='question',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
