# Generated by Django 2.0 on 2018-03-21 06:13

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('qa_web', '0006_auto_20180304_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
