# Generated by Django 2.0 on 2018-03-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_web', '0006_auto_20180304_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img'),
        ),
    ]
