# Generated by Django 2.0 on 2018-03-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_web', '0007_auto_20180321_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
